In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np

iris_dataset = load_iris()

x_train,x_test,y_train,y_test = train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

gbrt = GradientBoostingClassifier(learning_rate=0.01, random_state=0)
gbrt.fit(x_train,y_train)

print("Decision function shape:{}".format(gbrt.decision_function(x_test).shape))
print("Decision function:\n{}".format(gbrt.decision_function(x_test)[:6,:]))
print("Argmax of decision function:\n{}".format(np.argmax(gbrt.decision_function(x_test),axis=1)))
print("Predictions:\n{}".format(gbrt.predict(x_test)))
print("Predicted probabilities:\n{}".format(gbrt.predict_proba(x_test)[:6]))
print("Sums:{}".format(gbrt.predict_proba(x_test)[:6].sum(axis=1)))
print("Argmax of predicted probabilities:\n{}".format(np.argmax(gbrt.predict_proba(x_test),axis=1)))
#print("Test set score:{:.2f}".format(gbrt.score(x_test,y_test)))





Decision function shape:(38, 3)
Decision function:
[[-0.50692424 -0.53347791  1.53022838]
 [-0.51151707  1.50574741 -0.48234855]
 [ 1.51897822 -0.53079866 -0.48146442]
 [-0.50756256 -0.53347791  1.53022838]
 [ 1.51897822 -0.53079866 -0.48146442]
 [-0.50985911 -0.53347791  1.53022838]]
Argmax of decision function:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
Predictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
Predicted probabilities:
[[ 0.10370714  0.10098957  0.79530329]
 [ 0.10474133  0.7874172   0.10784147]
 [ 0.79111482  0.10186682  0.10701837]
 [ 0.10364782  0.10099625  0.79535593]
 [ 0.79111482  0.10186682  0.10701837]
 [ 0.10343465  0.10102027  0.79554508]]
Sums:[ 1.  1.  1.  1.  1.  1.]
Argmax of predicted probabilities:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
